name: Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Deploy container
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            bash scripts/deploy_preview.sh ${{ github.event.number }} $((30000 + ${{ github.event.number }}))
          else
            bash scripts/deploy_base.sh
